# -*- encoding: utf-8 -*-

=begin
#OneLogin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0-alpha.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "onelogin/version"

Gem::Specification.new do |s|
  s.name        = "onelogin"
  s.version     = OneLogin::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Onelogin DevEx"]
  s.email       = ["support@onelogin.com"]
  s.homepage    = "https://github.com/onelogin/onelogin-ruby-sdk"
  s.summary     = "OneLogin&#39;s Ruby SDK."
  s.description = "OneLogin&#39;s Ruby SDK. Use this API client to interact with OneLogin&#39;s platform"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
