=begin
#OneLogin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0-alpha.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneLogin::AuthMethod
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneLogin::AuthMethod do
  let(:instance) { OneLogin::AuthMethod.new }

  describe 'test an instance of AuthMethod' do
    it 'should create an instance of AuthMethod' do
      expect(instance).to be_instance_of(OneLogin::AuthMethod)
    end
  end
end
