=begin
#OneLogin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0-alpha.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetRateLimit200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetRateLimit200ResponseData do
  let(:instance) { OpenapiClient::GetRateLimit200ResponseData.new }

  describe 'test an instance of GetRateLimit200ResponseData' do
    it 'should create an instance of GetRateLimit200ResponseData' do
      expect(instance).to be_instance_of(OpenapiClient::GetRateLimit200ResponseData)
    end
  end
  describe 'test attribute "x_rate_limit_limit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "x_rate_limit_remaining"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "x_rate_limit_reset"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
