=begin
#OneLogin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0-alpha.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetUserApps200ResponseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetUserApps200ResponseInner do
  let(:instance) { OpenapiClient::GetUserApps200ResponseInner.new }

  describe 'test an instance of GetUserApps200ResponseInner' do
    it 'should create an instance of GetUserApps200ResponseInner' do
      expect(instance).to be_instance_of(OpenapiClient::GetUserApps200ResponseInner)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "icon_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "extension"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "login_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "provisioning_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["enabling", "disabling", "enabling_pending_approval", "disabling_pendding_approval", "enabled", "disabled", "disabling_failed", "enabling_failed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.provisioning_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "provisioning_state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["unknown", "provisioning", "modifying", "deleting", "provisioning_pending_approval", "deleting_pending_approval", "modifying_pending_approval", "linking", "provisioned", "deleted", "modifying_failed", "provisioning_failed", "deleting_failed", "linking_failed", "disabled", "nonexistent", "modifying_pending_approval_then_disabled"])
      # validator.allowable_values.each do |value|
      #   expect { instance.provisioning_state = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "provisioning_enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
