=begin
#OneLogin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0-alpha.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ListAuthorizationServers200ResponseInnerConfiguration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ListAuthorizationServers200ResponseInnerConfiguration do
  let(:instance) { OpenapiClient::ListAuthorizationServers200ResponseInnerConfiguration.new }

  describe 'test an instance of ListAuthorizationServers200ResponseInnerConfiguration' do
    it 'should create an instance of ListAuthorizationServers200ResponseInnerConfiguration' do
      expect(instance).to be_instance_of(OpenapiClient::ListAuthorizationServers200ResponseInnerConfiguration)
    end
  end
  describe 'test attribute "resource_identifier"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "audiences"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
