ONELOGIN_CLIENT_ID = Rails.application.secrets.ONELOGIN_CLIENT_ID
ONELOGIN_CLIENT_SECRET = Rails.application.secrets.ONELOGIN_CLIENT_SECRET
ONELOGIN_REGION = Rails.application.secrets.ONELOGIN_REGION
ONELOGIN_SUBDOMAIN = Rails.application.secrets.ONELOGIN_SUBDOMAIN
CUSTOM_DOMAIN = Rails.application.secrets.CUSTOM_DOMAIN
COOKIE_VIA_POST_FORM = Rails.application.secrets.COOKIE_VIA_POST_FORM
